### ISSUE TITLE
オンオフ機能実装

### ISSUE THREAD

**Issue by euphmat** [euphmat/input_Timecard#7]
ブラウザアクションに実装するのは面倒なので
おぷション画面に実装する

**Comment by empty-YK** [comment]
オプション画面に実装するより、アイコンを左クリックでONOFFできるのが一番使いやすいと感じる

**Comment by euphmat** [comment]
たし蟹

**Comment by euphmat** [comment]
> オプション画面に実装するより、アイコンを左クリックでONOFFできるのが一番使いやすいと感じる

たし蟹
実装できるかどうかの問題があるから一旦放置

**Comment by euphmat** [comment]
> オプション画面に実装するより、アイコンを左クリックでONOFFできるのが一番使いやすいと感じる

たし蟹
